version: '3'
services:
  fastapi:
    build:
      context: .
    ports:
      - "8050:8050"
    volumes:
      - .:/app
    networks:
      - library_network
    command: uvicorn main:app --host 0.0.0.0 --port 8050 --reload
    #command: gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8050 --timeout 180
  
  mongodb:
    image: mongo  # Usa la imagen oficial de MongoDB
    ports:
      - "27017:27017"  # Mapea el puerto 27017 del contenedor al host
    volumes:
      - mongodb_data:/data/db  # Persiste los datos en un volumen
    networks:
      - library_network

networks:
  library_network:  # Define una red para los servicios
    driver: bridge

volumes:
  mongodb_data:  # Define el volumen para almacenamiento persistente
